# dataset: "/home/touchair/kaist_urban_dataset/urban08"
dataset: "/home/mjm/MengJinming/MINS/Urban22"
# save_to: "/home/touchair/kaist_urban_dataset/urban08/bag"
save_to: "/home/mjm/MengJinming/MINS/Urban22/Bag"

# 高度计（气压计？）
altimeter: false
altimeter_topic: "/altimeter_data"

# 编码器
encoder: true
# wheel_odom_topic: "/wheel_odom"
# encoder_irp_topic: "/encoder_count"
encoder_raw_topic: "/joint_states"

# 雾传感器
fog: false
fog_topic: "/dsp1760_data"

# GPS
gps: true
gps_topic: "/gps/fix"

# 虚拟参考站系统,一种GPS增强技术（好像是一种RTK）
vrs: false
vrs_topic: "/vrs_gps_data"

# IMU
imu: true
# imu_irp_topic: "/xsens_imu_data"
imu_raw_topic: "/imu/data_raw"
# imu_mag_topic: "/imu/mag"

# Velodyne（机械激光雷达）
velodyne: true
velodyne_left_topic: "/ns2/velodyne_points"
velodyne_right_topic: "/ns1/velodyne_points"

# SICK(好像是单线激光雷达）
sick: false
sick_back_topic: "/lms511_back/scan"
sick_middle_topic: "/lms511_middle/scan"

# 双目相机
stereo: true
stereo_left_topic: "/stereo/left/image_raw"
stereo_right_topic: "/stereo/right/image_raw"
